打理
koishijs/koishi-plugin-og pull request #10
Opened 2024-05-01 16:46 UTC by jexjws

本PR：

- 把 `ctx.http.axios` 替换成了 `fetch then` 的形式，解决 #9 
- `h('image', { url })` 替换成了 `h('img', { src })` 的形式，解决图片无法在一些适配器正常发送的问题

2024-05-06 06:31 UTC, shigma requested changes
首先很感谢你的 PR。但如果你希望贡献给这个仓库，那么你不应该修改 README 和 package.json。正确的做法是自己改完自己直接发布。这不需要我的同意。

如果你已经改完并发布了你的版本，那么这个 PR 可以关闭了。否则，我会复原 README 和 package.json，然后更新这个插件。

2024-05-06 06:42 UTC, jexjws commented
我去，对不起对不起 
我只顾着推我的更改，忘了这个pr还没被合并，导致了我的fork更改意料之外的反映到了这个pr上（我应该新开一个分支，而不是在main上推更改，抱歉了
我现在就revert一下不应该的更改，以使你可以合并这个pr

2024-05-06 07:25 UTC, jexjws commented
ok

2024-05-08 13:48 UTC, shigma commented
> * 之所以不用 `ctx.http.get` 是因为我不知道怎么从 `ctx.http.get` 返回的 Response 里面提取出 headers 来，它好像直接返回 Response.body 了

```ts
const { data, headers } = await ctx.http()
```

我已经改好了

2024-05-08 13:49 UTC, shigma approved these changes

2024-05-08 13:49 UTC, merged

2024-05-08 13:51 UTC, shigma commented
发布了 1.3.0 版本。